# Generated by Django 5.0.14 on 2026-01-26 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Terminé'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('open_doors', models.PositiveIntegerField(default=0, verbose_name='Portes ouvertes')),
                ('knocked_doors', models.PositiveIntegerField(default=0, verbose_name='Portes frappées')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addresses', models.ManyToManyField(related_name='visits', to='mobilisation.address', verbose_name='Adresses')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
