# Generated by Django 5.0.14 on 2026-01-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilisation', '0002_address_is_finished_visit'),
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='territory.building', verbose_name='Immeuble (territoire)'),
        ),
    ]
