# Generated by Django 5.0.14 on 2026-01-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilisation', '0003_address_building'),
        ('territory', '0002_building_is_finished_building_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='addresses',
        ),
        migrations.AddField(
            model_name='visit',
            name='buildings',
            field=models.ManyToManyField(related_name='visits', to='territory.building', verbose_name='Immeubles'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
