# Generated by Django 5.2.9 on 2026-01-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilisation', '0004_remove_visit_addresses_visit_buildings_and_more'),
        ('territory', '0003_alter_votingdesk_options_votingdesk_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tractage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Nom du lieu')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Adresse')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('nb_tractage', models.PositiveIntegerField(default=0, verbose_name='Nombre de tractages')),
                ('type_tractage', models.CharField(choices=[('marche', 'Marché'), ('metro', 'Métro'), ('bus', 'Arrêt de bus'), ('commerce', 'Commerce'), ('ecole', 'École'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voting_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tractages', to='territory.votingdesk', verbose_name='Bureau de vote')),
            ],
            options={
                'verbose_name': 'Tractage',
                'verbose_name_plural': 'Tractages',
                'ordering': ['-nb_tractage', 'label'],
            },
        ),
    ]
