# Generated by Django 5.2.9 on 2026-02-03 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilisation', '0005_tractage'),
        ('territory', '0003_alter_votingdesk_options_votingdesk_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=200, verbose_name='Quartier')),
                ('reg21_expressed', models.PositiveIntegerField(default=0, verbose_name='REG21 Exprimés')),
                ('reg21_uge_votes', models.PositiveIntegerField(default=0, verbose_name='REG21 Voix UGE')),
                ('reg21_uge_percent', models.FloatField(default=0, verbose_name='REG21 % UGE')),
                ('reg21_abstention', models.FloatField(default=0, verbose_name='REG21 Abstention %')),
                ('euro24_expressed', models.PositiveIntegerField(default=0, verbose_name='EURO24 Exprimés')),
                ('euro24_nfp_votes', models.PositiveIntegerField(default=0, verbose_name='EURO24 Voix NFP')),
                ('euro24_nfp_percent', models.FloatField(default=0, verbose_name='EURO24 % NFP')),
                ('euro24_abstention', models.FloatField(default=0, verbose_name='EURO24 Abstention %')),
                ('leg24_expressed', models.PositiveIntegerField(default=0, verbose_name='LEG24 Exprimés')),
                ('leg24_nfp_votes', models.PositiveIntegerField(default=0, verbose_name='LEG24 Voix NFP')),
                ('leg24_nfp_percent', models.FloatField(default=0, verbose_name='LEG24 % NFP')),
                ('leg24_abstention', models.FloatField(default=0, verbose_name='LEG24 Abstention %')),
                ('delta_nfp_percent', models.FloatField(default=0, verbose_name='Delta % NFP LEG24-REG21')),
                ('voting_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_results', to='territory.votingdesk', verbose_name='Bureau de vote')),
            ],
            options={
                'verbose_name': 'Résultat électoral',
                'verbose_name_plural': 'Résultats électoraux',
                'ordering': ['voting_desk__code'],
                'unique_together': {('voting_desk',)},
            },
        ),
    ]
