# Generated by Django 5.2.9 on 2026-02-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilisation', '0006_electionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionresult',
            name='delta_nfp_percent',
        ),
    ]
