# Generated by Django 5.2.9 on 2026-03-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilisation', '0008_userprofile'),
        ('territory', '0004_building_is_hlm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_election', models.CharField(help_text='Format: 2020_muni_t1', max_length=50, unique=True, verbose_name='ID élection')),
                ('type_election', models.CharField(choices=[('muni', 'Municipales'), ('euro', 'Européennes'), ('légi', 'Législatives'), ('pres', 'Présidentielles'), ('cant', 'Cantonales'), ('regi', 'Régionales')], max_length=10, verbose_name='Type')),
                ('tour', models.CharField(choices=[('t1', 'Tour 1'), ('t2', 'Tour 2')], max_length=2, verbose_name='Tour')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Élection',
                'verbose_name_plural': 'Élections',
                'ordering': ['-year', 'type_election', 'tour'],
            },
        ),
        migrations.CreateModel(
            name='Nuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code nuance')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur (hex)')),
            ],
            options={
                'verbose_name': 'Nuance politique',
                'verbose_name_plural': 'Nuances politiques',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur (hex)')),
                ('nuances', models.ManyToManyField(blank=True, related_name='alliances', to='mobilisation.nuance', verbose_name='Nuances')),
            ],
            options={
                'verbose_name': 'Alliance',
                'verbose_name_plural': 'Alliances',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ElectionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstention_percent', models.FloatField(default=0, help_text='ratio_abstentions_inscrits', verbose_name='Abstention (%)')),
                ('blancs_percent', models.FloatField(default=0, help_text='ratio_blancs_votants', verbose_name='Blancs/nuls (% votants)')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='mobilisation.election', verbose_name='Élection')),
                ('voting_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='territory.votingdesk', verbose_name='Bureau de vote')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'ordering': ['election', 'voting_desk__code'],
                'unique_together': {('election', 'voting_desk')},
            },
        ),
        migrations.CreateModel(
            name='NuanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_voix_exprimes', models.FloatField(default=0, verbose_name='% voix exprimées')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuance_results', to='mobilisation.election', verbose_name='Élection')),
                ('nuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mobilisation.nuance', verbose_name='Nuance')),
                ('voting_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuance_results', to='territory.votingdesk', verbose_name='Bureau de vote')),
            ],
            options={
                'verbose_name': 'Résultat par nuance',
                'verbose_name_plural': 'Résultats par nuance',
                'ordering': ['election', 'voting_desk__code', '-ratio_voix_exprimes'],
                'unique_together': {('election', 'voting_desk', 'nuance')},
            },
        ),
    ]
