# Generated by Django 5.2.9 on 2026-03-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobilisation", "0015_rename_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="election_code",
            field=models.CharField(
                help_text="Format: 2020_muni_t1",
                max_length=50,
                unique=True,
                verbose_name="Code élection",
            ),
        ),
    ]
