# Generated by Django 5.2.9 on 2026-01-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VotingDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('location', models.CharField(max_length=200, verbose_name='Localisation')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_desks', to='territory.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Bureau de vote',
                'verbose_name_plural': 'Bureaux de vote',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=20, verbose_name='Numéro')),
                ('street_name', models.CharField(max_length=200, verbose_name='Rue')),
                ('num_electors', models.PositiveIntegerField(default=0, verbose_name="Nombre d'électeurs")),
                ('voting_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='territory.votingdesk', verbose_name='Bureau de vote')),
            ],
            options={
                'verbose_name': 'Immeuble',
                'verbose_name_plural': 'Immeubles',
                'ordering': ['street_name', 'street_number'],
                'unique_together': {('voting_desk', 'street_number', 'street_name')},
            },
        ),
    ]
