# Generated by Django 5.0.14 on 2026-01-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Terminé'),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
