# Generated by Django 5.2.9 on 2026-01-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0002_building_is_finished_building_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingdesk',
            options={'ordering': ['priority', 'code'], 'verbose_name': 'Bureau de vote', 'verbose_name_plural': 'Bureaux de vote'},
        ),
        migrations.AddField(
            model_name='votingdesk',
            name='priority',
            field=models.PositiveIntegerField(blank=True, help_text='1 = priorité maximale', null=True, verbose_name='Priorité'),
        ),
    ]
