# Generated by Django 5.2.11 on 2026-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territory", "0003_alter_votingdesk_options_votingdesk_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="is_hlm",
            field=models.BooleanField(
                default=False, verbose_name="Logement social (HLM)"
            ),
        ),
    ]
