# Generated by Django 5.2.9 on 2026-03-24 20:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territory", "0004_building_is_hlm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBuilding",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "street_number",
                    models.CharField(max_length=20, verbose_name="Numéro"),
                ),
                ("street_name", models.CharField(max_length=200, verbose_name="Rue")),
                (
                    "num_electors",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'électeurs"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Terminé"),
                ),
                (
                    "is_hlm",
                    models.BooleanField(
                        default=False, verbose_name="Logement social (HLM)"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voting_desk",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="territory.votingdesk",
                        verbose_name="Bureau de vote",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Immeuble",
                "verbose_name_plural": "historical Immeubles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
